project_id: 527866
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: website/README.md
    translation: /website/%file_name%.%locale%.%file_extension%
  - source: /CHANGELOG.md
    translation: /%file_name%.%locale%.%file_extension%
